### ISSUE TITLE
missing L(f(x ∗ ); θ), y) 

### ISSUE THREAD

**Issue by yuval-neh** [VITA-Group/AugMax#13]
in the paper the total loss(equation 5) - 1/2[L(f(x∗); θ), y) + L(f(x); θ), y)] + λLc(x, x∗) 
but in the implementation you only use  L(f(x); θ), y) + λLc(x, x∗). which is the correct equation?

**Comment by htwang14** [comment]
Hi, they have similar performance, since Lc(x,x*) encourages f(x) and f(x*) to be similar. You can use the code implementation to reproduce results. Thank you!
