### ISSUE TITLE
Use custom dataset

### ISSUE THREAD

**Issue by Yahya222** [VITA-Group/AugMax#2]
Hello,
Thank you for this code it is really helpful. I have a question is it possible to use the same code with custom dataset?
If so please tell me what to change.
Best regards

**Comment by htwang14** [comment]
Yes, you can use AugMax on your own dataset, as long as the augmentations make sense on it. 
For implementation, you need to:
1. Create a file named `your_dataset_name.py` under `AugMax/dataloaders`
2. Define your own dataset class as an inheritance of `torch.utils.data.Dataset` in `your_dataset_name.py`. Here is a [official tutorial from PyTorch](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html) on how to do it. 
3. Write the dataloader code for your own dataset in `your_dataset_name.py`. You can take [my CIFAR10 dataloader](https://github.com/VITA-Group/AugMax/blob/b83adacb97cbc8a8feaec00844d9ea23b36265c9/dataloaders/cifar10.py#L8) as an example. 
4. Import your own dataloader function and load data as I did for CIFAR10 in `augmax_training_ddp.py`.
